# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-09-27 07:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ar', models.CharField(max_length=50)),
                ('prenom_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_trans', models.CharField(blank=True, max_length=40, null=True)),
                ('prenom_trans', models.CharField(blank=True, max_length=80, null=True)),
                ('naiss_date', models.CharField(blank=True, max_length=10, null=True)),
                ('deces_date', models.CharField(blank=True, max_length=10, null=True)),
                ('naiss_hej', models.CharField(blank=True, max_length=10, null=True)),
                ('deces_hej', models.CharField(blank=True, max_length=10, null=True)),
                ('naiss_lieu', models.CharField(blank=True, max_length=20, null=True)),
                ('deces_lieu', models.CharField(blank=True, max_length=20, null=True)),
                ('biographie', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'managed': True,
                'db_table': 'sara_auteurs',
            },
        ),
        migrations.CreateModel(
            name='Bibliographie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zotero', models.CharField(blank=True, max_length=50, null=True)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('page', models.CharField(blank=True, max_length=25, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'managed': True,
                'db_table': 'bibliographie',
            },
        ),
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_origin', models.CharField(blank=True, max_length=100)),
                ('nom_abbrev', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=40)),
                ('ville', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'managed': True,
                'db_table': 'sara_bibliotheques',
                'verbose_name_plural': 'Bibliothèques',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_ar', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'managed': True,
                'db_table': 'sara_textes_categories',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Copie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numincorpus', models.IntegerField()),
                ('folios', models.CharField(max_length=20)),
                ('folio_begin', models.CharField(max_length=10)),
                ('folio_end', models.CharField(max_length=10)),
                ('auteur', models.CharField(max_length=30)),
                ('titre', models.CharField(max_length=70)),
                ('copiste', models.CharField(max_length=60)),
                ('date_hej', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=40)),
                ('lieu', models.CharField(max_length=30)),
                ('commentaires', models.TextField()),
                ('incipit', models.CharField(max_length=200)),
                ('explicit', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'managed': True,
                'db_table': 'sara_copies_textes',
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=25)),
                ('cote', models.IntegerField()),
                ('ancienne_cote', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('id_biblio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatext.Bibliotheque')),
            ],
            options={
                'managed': True,
                'db_table': 'sara_corpus',
                'verbose_name_plural': 'Corpus',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, null=True)),
                ('contenu', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'managed': True,
                'db_table': 'sara_sections',
            },
        ),
        migrations.CreateModel(
            name='Texte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ar', 'العربيّة'), ('fr', 'français')], default='ar', max_length=2)),
                ('titre_ar', models.CharField(max_length=150)),
                ('titre_trans', models.CharField(blank=True, max_length=100, null=True)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('catalogue1', models.CharField(blank=True, choices=[('AWi', 'AWi'), ('AWii', 'AWii'), ('النّقشبندي', 'النّقشبندي'), ('Adler', 'Adler')], max_length=10, null=True)),
                ('ref1', models.CharField(blank=True, max_length=10, null=True)),
                ('catalogue2', models.CharField(blank=True, choices=[('AWi', 'AWi'), ('AWii', 'AWii'), ('النّقشبندي', 'النّقشبندي'), ('Adler', 'Adler')], max_length=10, null=True)),
                ('ref2', models.CharField(blank=True, max_length=10, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('id_auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatext.Auteur')),
                ('id_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datatext.Categorie')),
            ],
            options={
                'managed': True,
                'db_table': 'sara_textes',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='texte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datatext.Texte'),
        ),
        migrations.AddField(
            model_name='copie',
            name='id_corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatext.Corpus'),
        ),
        migrations.AddField(
            model_name='copie',
            name='id_texte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatext.Texte'),
        ),
        migrations.AddField(
            model_name='bibliographie',
            name='id_texte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatext.Texte'),
        ),
    ]
